all:
  vars:
    ansible_user: "admin"
    ansible_password: "password"
    ansible_python_interpreter: python
    ansible_httpapi_validate_certs: false
    ansible_httpapi_use_ssl: true
  children:
    ndfc:
      vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: cisco.dcnm.dcnm
      hosts:
        nac-ndfc1:
          ansible_host: 10.0.55.128
