---
- hosts: ndfc
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    ansible_switch1: 192.168.2.4
    ansible_switch2: 192.168.2.5
    ansible_switch3: 192.168.2.6
    ansible_it_fabric: test-fabric
    deploy: false
    switch_username: admin
    switch_password: password

  roles:
    - dcnm_inventory
  tags: always
