---
# This playbook can be used to execute integration tests for
# the role located in:
#
# tests/integration/targets/dcnm_policy
#
# Modify the vars section with details for your testing setup.
#
- name: Play for dcnm
  hosts: dcnm
  gather_facts: false
  connection: ansible.netcommon.httpapi

  vars:
    # Uncomment 'testcase:' to run a specific test under 'tests/integration/targets/dcnm_policy/tests/dcnm'
    # testcase: dcnm_policy_with*
    ansible_it_fabric: test_fabric
    ansible_switch1: 192.168.55.21
    ansible_sw1_sno: 9YEXD0OHA7Z
    ansible_switch2: 192.168.55.22
    ansible_sw2_sno: 9M2TXMZ7D3N

  roles:
    - dcnm_policy
